### PR TITLE
Fix minor beam physics

### PR DESCRIPTION
**Pull request by DavidSagan**
Minor documentation clarification for gridOriginOffset coordinates.

### CODE REVIEW

**Comment by ax3l** [comment]
@DavidSagan thanks for the update, can you please resolve the merge conflict?

**Review by ChristopherMayes — APPROVED** [review]

**Comment by DavidSagan** [comment]
@ax3l OK conflict resolved.

**Comment by ChristopherMayes** [comment]
@ax3l Could this get merged?

**Review by ax3l — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
