### PR TITLE
Domex neutron raytracing

### PR DESCRIPTION
**Pull request by CFGrote**
*Please add a brief description (one sentence) here and link the issue this pull-request implements*

*Implements issue:* #...

## Description

*As detailed description as possible.*

*What is introduced, removed or renamed and why?*
*What is made required, recommended, optional?*
*What concept stands behind this change?*

*Please also add an example.*

## Affected Components

- `base`
- `EXT-...`

## Logic Changes

*Which logic changes are conceptually introduced?*

## Writer Changes

*How does this change affect data writers?*
*What would a writer need to change?*
*Does this pull request change the interpretation of existing data writers?*

- `libopenPMD` (upcoming): https://github.com/ComputationalRadiationPhysics/libopenPMD/...

## Reader Changes

*How does this change affect data readers?*

*What would a reader need to change? Link implementation examples!*

- `openPMD-validator`: https://github.com/openPMD/openPMD-validator/...
- `openPMD-viewer`: https://github.com/openPMD/openPMD-viewer/...
- `yt`: https://github.com/yt-project/yt/...
- `VisIt`: https://github.com/openPMD/openPMD-visit-plugin
- `libopenPMD` (upcoming): https://github.com/ComputationalRadiationPhysics/libopenPMD/...
- `XDMF` (upcoming): https://github.com/openPMD/openPMD-tools/...

## Data Converter

*How does this affect already existing files with previous versions of the standard?*
*Is this change possible to be expressed in a way, that an automated tool can update the file?*
*Link code/pull requests that implement the upgrade logic!*

- https://github.com/openPMD/openPMD-converter/...

### CODE REVIEW

**Comment by ax3l** [comment]
Hi @CFGrote and @mads-bertelsen!

Thank you for the proposal! Did you accidentally close the PR?

**Comment by mads-bertelsen** [comment]
@ax3l, yes it is definitely still in a draft state. I expected to submit it on Monday after finishing up the standard questions in the template that was provided.

**Comment by CFGrote** [comment]
hi ax3l,
i did not mean to submit the PR to the upstream repo but to our internal
fork for development, sorry for the confusion.

we will make a new PR once we're done from our end.

thanks, carsten

**Comment by ax3l** [comment]
Hi Carsten,

no problem, I was just wondering if something went wrong. Looking forward to your PR! :)

**Comment by ax3l** [comment]
@CFGrote Just a gentle/curious reminder. Social media told me you completed the extension, congrats! Feel free to open a PR hereto anytime :)

**Comment by DavidSagan** [comment]
@mads-bertelsen @CFGrote @ax3l 
This looks similar to the proposed Beam Physics extension. Would it not be better to merge these into one? Then there would be less duplication of effort in developing readers/writers and things would be more portable.

**Comment by ax3l** [comment]
I am not sure, @CFGrote extension is quite concise and focused to the use case they have. It does not need additions to readers/writers on the base standards as far as I saw, since it mainly defines additional namings & attributes.

Anyway, he can definitely comment more on that and I guess we can check for at least good compatibility when the PR is open :)

Refs.:
- https://github.com/PaNOSC-ViNYL/openPMD-standard/blob/upcoming-2.0.0/EXT_PRAYTRACE.md
- https://github.com/PaNOSC-ViNYL/openPMD-standard/tree/upcoming-2.0.0

**Comment by ax3l** [comment]
@CFGrote P.S. please do not forget to add your projects to https://github.com/openPMD/openPMD-projects :)

**Pull request closed without merging**
