### PR TITLE
Update Authors: Chris & Affil.

### PR DESCRIPTION
**Pull request by ax3l**
Add Christopher as the co-author of the beam physics extension `EXT:BeamPhysics` in #183.

Updated Stephan's affiliation. Add Ivo's middle name he uses in scientific work.

### CODE REVIEW

**Comment by ax3l** [comment]
@ChristopherMayes please tell me if you like another spelling or affiliation, etc. :)

**Review by skuschel — APPROVED** [review]

**Review by RemiLehe — APPROVED** [review]

**Comment by ChristopherMayes** [comment]
I usually prefer full affiliations. SLAC should really be: "SLAC National Accelerator Laboratory"

**Comment by ax3l** [comment]
From our email exchange:
> I just abbreviated affliliations all in these cases for simplicity and easier recognition. On slides and usually DOI meta data I put the long form of all.
>
> If you are ok with that I would keep it like this in this little in-source list? Will add a zenodo file (the CERN service we use for DOIs) soon as well, that will get the long form.

**Comment by ax3l** [comment]
I just added a full affiliation list below :)

**Comment by DavidSagan** [comment]
@ax3l FYI: Typical is to use "Cornell" instead of "CU" for the abbreviation (don't want to get confused with Columbia University, etc.).

**Comment by ax3l** [comment]
@DavidSagan oh sorry, did only find this: https://cals.cornell.edu/about/leadership/marketing-communications/style-guide/#university Fixed!

**Review by RemiLehe — APPROVED** [review]

**Comment by ax3l** [comment]
@DavidSagan @ChristopherMayes Updated with affiliation index :) Pls confirm if this is better now.

**Comment by DavidSagan** [comment]
@ax3l Looks good! Thanks.

**Pull request merged**
